elastic_client_config:
  elastic_protocol: https
  elastichost: '18.209.240.217'
  elasticPrefix: ''
  elasticport: '9200'
  elasticUser: 'elastic'
  elasticIndex: 'voice'
  actions: []
  fileRecordCount: 160000
  fileCounter: 0
query_config:
  index: 'voice'
  base_query_path: './queries'
  query_list:
    - get_sms_vodafone


